### ISSUE TITLE
Using TPPM with The Magic Dragon

### ISSUE THREAD

**Issue by TapMeDead** [sharkykh/tppm#41]
Hi, just a question. When using The Magic Dragon addon with Kodi, every movie I watch becomes a link in TPPM, when they are fully watched, they show as 90% on the TPPM page and I have to remove those manually. They do not show as having a resume point in Dragon or other addons, only on the TPPM webpage.
Also for some reason there are links on TPPM webpage showing as 0%, also from Magic Dragon, I think those are movies I start but don't watch more than a minute or less before deciding not to watch them. Or maybe they show like that after watching their Trailer.
So my question is, is this a Magic Dragon problem, or is it a TPPM problem somehow?
No other addons do this so I'm thinking Dragon does something strange.

**Comment by sharkykh** [comment]
**This app doesn't have anything to do it.** All it does is show whatever data Trakt provides and lets you to clear it.
I have never heard of "Magic Dragon", but it sounds like it's scrobbling to Trakt in the same way that the official Trakt addon does.

> when they are fully watched, they show as 90% on the TPPM page and I have to remove those manually

Sounds like that addon doesn't consider 90% watched to be completely watched, and sends "Pause" rather than "Stop" to Trakt. [Sending "Stop" with a progress of 80% or higher to Trakt will mark the item as watched.](https://trakt.docs.apiary.io/#reference/scrobble/stop/stop-or-finish-watching-in-a-media-center)

> Also for some reason there are links on TPPM webpage showing as 0%, also from Magic Dragon, I think those are movies I start but don't watch more than a minute or less before deciding not to watch them. 

You're probably correct, and it's part of the reason I made this app.
On the official Trakt addon [there is a setting for this](https://github.com/trakt/script.trakt/issues/347#issuecomment-619393525), I don't know if you can find one in the addon you are using.

**Comment by TapMeDead** [comment]
@sharkykh 
Thanks for the reply, and thank you for the app here, I use it quite often, because I watch a LOT of movies and shows heh.
Seems like Magic Dragon has some issues, it's a great addon though, I just have to remember to go to TPPM now and then to clear up all the crap from MD lol.
I am unsure if I can find the github for MD, I think I tried a while back but only found other older addons.
Anyway, thanks again :) very useful reply, will try some things later on.
