### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by amilino** [sharkykh/tppm#7]
Since some days I am receiving a lot of timeouts. Any ideas?

**Comment by sharkykh** [comment]
Unfortunately, Trakt has good days and bad days in terms of its' response times.
My application can't work when Trakt's API service times out, and because it requires the most updated information every time - caching is pretty much useless.

I will increase the "timeout" threshold, from the default 10 seconds to 30,
hopefully this will help a bit.

**Comment by sharkykh** [comment]
There are also some 5xx (502, 503) errors from Trakt servers, which I can't do anything about,
and sometimes they reject the requests from the browser for no good reason (it says some CORS error, but usually it works just fine).

Sorry... I wish it could be more reliable.

Anyway, [the updated version is now up](https://sharkykh.github.io/tppm/), timeouts should happen less.
